### ISSUE TITLE
Considering moving test logic into new package: `aqueduct_test`

### ISSUE THREAD

**Issue by kevmoo** [stablekernel/aqueduct#391]
Folks using aqueduct pull in all of `package:test` dependencies, even if they don't test.

Here's the list of things that disappear when removing test as a "regular" dependency

```
- barback 0.15.2+14
- boolean_selector 1.0.2
- http_multi_server 2.0.4
- io 0.3.2+1
- js 0.6.1
- mime 0.9.6
- multi_server_socket 1.0.1
- node_preamble 1.4.0
- package_resolver 1.0.2
- pool 1.3.4
- shelf 0.7.2
- shelf_packages_handler 1.0.3
- shelf_static 0.2.7
- shelf_web_socket 0.2.2
- source_map_stack_trace 1.1.4
- source_maps 0.10.4
- stream_channel 1.6.3
- term_glyph 1.0.0
- test 0.12.31
- web_socket_channel 1.0.7
```

https://github.com/dart-lang/mono_repo is your friend here!

**Comment by kevmoo** [comment]
Inspiration

https://github.com/dart-lang/angular/tree/master/angular_test
https://github.com/dart-lang/build/tree/master/build_test

**Comment by joeconwaystk** [comment]
This is definitely of interest. I felt real gross putting package:test in the standard dependencies just to support the test library. My fear was that people wouldn't test because they wouldn't find the test package. In hindsight, since everyone is going to create a project from the CLI anyway, the default project can include it as a dev dependency.

**Comment by kevmoo** [comment]
> the default project can include it as a dev dependency.

Exactly!

**Comment by joeconwaystk** [comment]
Completed and will push to pub once all test suites can be added back in for dart2.

**Comment by kevmoo** [comment]
Sweet!
