### ISSUE TITLE
Transactions don't have easy way of getting results.

### ISSUE THREAD

**Issue by halldors** [stablekernel/aqueduct#501]
Hi, I'm playing around with this framework, and liking it so far.

One thing I noticed is that to me the most natural thing for the transaction would be to return the object that the transactionBlock (the closure) returned. I took it for granted, and spent an hour debugging why I got null from that transaction.
To me this is the most natural way of doing the transaciton. 

```
final user = context.transaction((context) async {
    // ... some stuff
  return await myNewUser.insert();  
});
```

But we have to do this in Aqueduct ( this feels like an anti-pattern to me, coming from semi functional languages such as Swift and Kotlin) 
```
var user;
final rollbackReason = await context.transaction((context) async {
    // ... some stuff
  user = await myNewUser.insert();  
});
```

Returning the return from the context has even more nicer things going for it like this.

```
Future<User> createNewUser(context, user) async => context.transaction((context) async {
      // ... some stuff
    return await user.insert();  
  });
```

**Comment by joeconwaystk** [comment]
I agree to an extent, and this feature was initially designed the way you have it described here. I'm not sure the current solution is the best solution, but I can take you thru the thought process around some additional use cases and perhaps we can come up with something better.

The two big questions were: 

1. How should the user expect a rollback to behave?
2. What happens when you want to access values scoped to the transaction block from outside the transaction block scope?

Right now, if an exception is thrown within a transaction, the transaction itself throws. If rolling back the transaction, you can either return the rollback reason (like it does now) or throw an exception. Ideally, you would never have to wrap transactions in a try-catch block - if you get an exception, the error is caught by the controller and appropriate response is sent. If rollbacks become exceptions (because they can no longer be returned), many more transactions require a try-catch block, and the same variable scope escaping problem occurs.

In the event of returning an inserted object (or list of inserted objects of the same type) from a transaction, your proposed change makes a lot of sense.  But, this scales oddly when you have multiple, distinct values you want to escape the transaction closure. For example, this feels really inconsistent:

```dart
Type1 otherObject;
Type2 object = await context.transaction((ctx) async {
  otherObject = await ctx.insertObject(...);
  return ctx.insertObject(...);
});
```

If Dart had language level support for tuples, this would be a no brainer. One solution is to return a map, but I'd argue that's semantically the same as declaring variables outside of the scope of the transaction and assigning them within the transaction.

I'm interesting in hearing other solutions, too.

**Comment by halldors** [comment]
I understand the concerns.  
I'm coming from Spring Java mostly, and most of the time, we would annotating an method with `@Transactional` and all operations inside that method would be run in a transaction. And that method only returns one object, since being Java. 
Rollback happens on any RuntimeException, and most of the time, we don't care about the rollback reason more then any other data integrity errors and they being exceptions. The operation fails(and aborted) or succeeds.
I think this works mostly quite well. If you really need to return more things, you can always create an dto object for it.

Other thing, a nice feature would be to have an optional "retry: n" parameter in the transaction, that would retry the transaction block n number of times on failures. You would not want to do that if the transaction pattern encourages  non pure transaction blocks (except for the sql statemets).

**Comment by joeconwaystk** [comment]
I think you've made a convincing argument. Does a perfect solution mean that rollbacks throw (and you could capture the reason in the catch if need be) and you have a dynamic return value from the transaction block? This work would have to be done prior to releasing 3.0, but it isn't a lot of work.

Retries are also a great idea. These can be added anytime after 3.0. Can you elaborate on non-pure transaction blocks? Do you mean having other Dart executable code within the block?

**Comment by halldors** [comment]
What I mean is that code in the transaction block shouldn't mutate any state outside the block. But it is perfectly fine to run other Dart code, calculations and stuff.

It would be awesome to have the transaction method as a generic function. One could of course skip the generic argument and dart will fallback to dynamic.

Something like this.
```
// Here providing type information.
User context.transaction<User>((context) async {
//...
  return await user.insert();
});

// Skipping the generic argument is valid (I think) and Dart will fallback to dynamic.
dynamic context.transaction((context) async {
  return await user.insert();
});
```

**Comment by joeconwaystk** [comment]
👍
