### ISSUE TITLE
Upgrade Of Dependencies Needed

### ISSUE THREAD

**Issue by Gee5ive** [stablekernel/aqueduct#587]
Hi. version 3.0.2 of aqueduct is using a few pinned versions of outdated dependencies which causes problems in projects using other commonly used libraries in the dart ecosystem, namely [built_value](https://pub.dartlang.org/packages/built_value)  and [validators](https://pub.dartlang.org/packages/validators).

The conflicting dependencies are 
analyzer: '>=0.32.0 <0.33.0'
in both aqueduct and isolate_executor 2.0.1 .

I would have updated this myself and submitted a pr , but I'm assuming there are other dependency issues to be solved with the test libs as well. I have updated the dependencies in my local copy so far and have not seen any issues but I haven't ran any tests so far.

Thanks.

**Comment by joeconwaystk** [comment]
3.1.0-beta.1 is available on pub and has updated constraints on analyzer to include newer versions.

**Comment by AlexKenbo** [comment]
Resolving dependencies...
Because build_runner >=1.10.0 depends on build_resolvers ^1.3.8 which depends on analyzer ^0.39.5, build_runner >=1.10.0 **requires analyzer ^0.39.5**.
And because aqueduct >=3.3.0 depends on analyzer >=0.32.0 <0.36.0, build_runner >=1.10.0 is incompatible with aqueduct >=3.3.0.
So, because mdi_web depends on both aqueduct 3.3.0 and build_runner 1.10.0, version solving failed.
