### ISSUE TITLE
Memory usage higher than expected

### ISSUE THREAD

**Issue by lukepighetti** [stablekernel/aqueduct#617]
Hi everyone, 

I am comparing `Dart + Aqueduct` to `Node + Express` for simple containerized get-only APIs. My Aqueduct container uses 300mb of RAM while my Express container uses about 60-70mb. 

Is this a Dart issue? An Aqueduct issue? What kind of RAM use should we expect from a healthy Aqueduct container? 

In my case, I am only using it for routes and path controllers. I do have a little in-memory cache but the data contained within is only about 2-3mb.

Here's the source for the Aqueduct server. https://github.com/lukepighetti/hn-dart/tree/server/aqueduct

**Comment by lukepighetti** [comment]
I switched to using a snapshot with 1 instance and its now around 80-100mb

**Comment by joeconwaystk** [comment]
This is primarily a Dart issue. Dart 2 more or less tripled the memory consumption at runtime. It has to do with size of code in all imported packages, and in particular, aqueduct uses `package:analyzer` which represents a lot of it. The other issue is that each isolate has its own copy of the code instead of sharing it, which I understand is being fixed by the Dart team.

You can use snapshots to reduce this: https://github.com/dart-lang/sdk/wiki/Snapshots.

**Comment by joeconwaystk** [comment]
:+1: If you do some additional digging and see how node.js clustering impacts memory consumption, I'd be interested. This is definitely something I hope is improved in Dart. I will close this.
