### ISSUE TITLE
Complete documentation for File upload

### ISSUE THREAD

**Issue by thulani196** [stablekernel/aqueduct#704]
Kindly complete the multiprt/form-dat tutorial found at https://aqueduct.io/docs/http/request_and_response/#example-multipartform-data at least to the point of storing files in a specific location. I think that way it will provide a more clearer and beginner friendly guide, at the current state am finding it challenge knowing what to do with **headers** and **content** in the example.

**Comment by Arjunraj-k** [comment]
The file upload part is poorly documented. I cannot find a way to understand it. please make it more clear.

**Comment by joeconwaystk** [comment]
It'd be great to have a full tutorial for managing file storage. However, a couple of things:

1. Avoid persisting files on the same instance as your application server. Modern infrastructure uses transient instances to schedule and load balance your application server, and the filesystem is not permanent. You'll lose all of your files when a managed service reschedules your application, and in a multi-instance scenario (common) you will have different file systems. A service like Google Cloud Storage, Amazon S3, or Azure Blob Storage is preferable.

2. The headers and content of a multipart request are documented in the HTTP specification and many other places on the internet. While it'd be great to collect that information into this tutorial, an external contributor would have to do this for now. Because this information is standard across all frameworks & server implementations and available freely, we do not have the resources to provide this in the tutorial in a reasonable timeline.

**Comment by Arjunraj-k** [comment]
Here is an answer on stack overflow.

https://stackoverflow.com/questions/54965027/how-can-i-write-uploaded-multipart-files-to-disk

**Comment by thulani196** [comment]
> Here is an answer on stack overflow.
> 
> https://stackoverflow.com/questions/54965027/how-can-i-write-uploaded-multipart-files-to-disk

Hai @Arjunraj-k , the solution you provided works perfectly thanks a lot!.

**Comment by thulani196** [comment]
> It'd be great to have a full tutorial for managing file storage. However, a couple of things:
> 
> 1. Avoid persisting files on the same instance as your application server. Modern infrastructure uses transient instances to schedule and load balance your application server, and the filesystem is not permanent. You'll lose all of your files when a managed service reschedules your application, and in a multi-instance scenario (common) you will have different file systems. A service like Google Cloud Storage, Amazon S3, or Azure Blob Storage is preferable.
> 2. The headers and content of a multipart request are documented in the HTTP specification and many other places on the internet. While it'd be great to collect that information into this tutorial, an external contributor would have to do this for now. Because this information is standard across all frameworks & server implementations and available freely, we do not have the resources to provide this in the tutorial in a reasonable timeline.

Thank you for the insight @joeconwaystk . I get your point. I will use @Arjunraj-k solution for development for and will later look into hosting files in the cloud as I approach production.

**Comment by Arjunraj-k** [comment]
> > Here is an answer on stack overflow.
> > https://stackoverflow.com/questions/54965027/how-can-i-write-uploaded-multipart-files-to-disk
> 
> Hai @Arjunraj-k , the solution you provided works perfectly thanks a lot!.

Nice to hear that. you must thank the man who provided the answer on stack overflow

**Comment by mrleeT91** [comment]
Im newbie at dev, sorry about this dumb question. I try to copy and run code in here [.](https://stackoverflow.com/questions/54965027/how-can-i-write-uploaded-multipart-files-to-disk)
What is filepath in here, why i get error file when i try upload image by postman like this :( 

"[SEVERE] aqueduct: POST /crm/upload 14764ms 500 {user-agent : PostmanRuntime/7.22.0\nconnection : keep-alive\naccept : */*\ncache-control : no-cache\npostman-token : d67ec90e-b190-4eeb-9b31-968asdq21\naccept-encoding : gzip, deflate, br\ncontent-length : 64740\nhost : localhost:8888\ncontent-type : multipart/form-data; boundary=--------------------------564333675847120492374912364\n}  FileSystemException: Cannot open file, path = 'data/2020-03-02 11:07:14.948920.jpg' (OS Error: The filename, directory name, or volume label syntax is incorrect."
