### ISSUE TITLE
Add ability to quote or specify column name

### ISSUE THREAD

**Issue by carmas123** [stablekernel/aqueduct#717]
Hi, I'm new in Aqueduct and on my first project I found some problem to use my database structure and PostgreSQL. I know that in postgres when you don't quote with " the columns name postgress convert in lowercase and considering that postgres is case-sensitive with column name, this is a problem when I have a db structure with uppercase chars.
Now my idea is to quote always the column names to bypass this problem.
Into `query_builder.dart` we have a method `sqlColumnName` that can help to solve this problem. Regards and have a nice day to all.

Another solution can be to add into `@Column` annotation a property to specify the real column name to be able to specify manually the column name.

**Comment by joeconwaystk** [comment]
I agree on being able to select different names for columns than the default (#693). 

Is the issue you are seeing that the tables were created using quoted column names? PostgreSQL columns aren't case-sensitive unless they are quoted when creating the table. That is, this is valid:

```
postgres=# create table t (cOl int);
CREATE TABLE
postgres=# insert into t (col) values (1);
INSERT 0 1
```

But this is not:

```
postgres=# create table t ("cOl" int);
CREATE TABLE
postgres=# insert into t (col) values (1);
ERROR:  column "col" of relation "t" does not exist
```

Are you able to rename column names in your database so that they are not quoted?

**Comment by carmas123** [comment]
mmm sorry man but I'm new in PostgreSQL, I'm going to investigate that.
Thank you so much.

**Comment by Pants44** [comment]
After originally looking at Issue #693, its not clear that this is currently possible yet. Is the ability to specify the column name available in the @column annotation?
