### ISSUE TITLE
join in query cause error in fetchOne

### ISSUE THREAD

**Issue by mariogorki94** [stablekernel/aqueduct#724]
final q = Query<DailyReport>(dbContext)
      ..where((dt) => dt.user.id).equalTo(user)
      ..where((dt) => dt.organization.id).equalTo(organization)
      ..join(set: (dt) => dt.tasks)
      ..join(object: (dt) => dt.user)
      ..sortBy((dt) => dt.reportDate, QuerySortOrder.descending);

q.fetchOne();
throws an exception that more than one result is returned in fetchOneClause. If i remove 
 ..join(set: (dt) => dt.tasks) everything works fine.  Tried using fetchLimit = 1 and the query returns the row but the joined subquery is limited to 1 not the original query

**Comment by joeconwaystk** [comment]
Setting `fetchLimit` adds the keyword `LIMIT` to the SQL query. `fetchOne` sets the `fetchLimit` to 1 if querying one table, but cannot set this limit on a query that joins multiple tables, because the fetch limit would restrict the joined rows as well. If you use `fetchOne` while joining, an error is thrown if you fetch more than one top-level object (the table the outer query is on). I'd suggest changing this to fetch and seeing which rows actually come back. You can also enable query logging to see the query being generated and its results so you can run it/modify it against your own database:

```dart
// In your app channel
Future prepare() async {
  hierarchicalLoggingEnabled = true;
  Logger("aqueduct")
    ..level = Level.ALL
    ..onRecord.listen((p) => print("$p ${p.object} ${p.stackTrace}"));
}
```

**Comment by mariogorki94** [comment]
Thanks
