### ISSUE TITLE
dart2native support

### ISSUE THREAD

**Issue by ansarizafar** [stablekernel/aqueduct#738]
Is there any plan to support newly released dart2native compiler?

**Comment by DavidBernal** [comment]
And AOT. Interesting to serverless.

**Comment by joeconwaystk** [comment]
Yes! See https://github.com/stablekernel/aqueduct/issues/669.

**Comment by rknell** [comment]
Thanks joeconwaystk.

My motivation for dart2native is we do a lot of outsourced enterprise work and I have a bunch of server applications that would greatly be improved if I could just ship a binary to my customers. Plus I think scaling should be easier if I can just fire up a new linux box and run a single binary instead of worrying about a complex environment or containerisation.

I wanted to add that here instead of #669 as even AOT didn't solve that issue for me.

**Comment by ansarizafar** [comment]
@rknell Have you complied any of your enterprise app with dart2native. Could you please share information about performance, memory and cpu usages? Dart team is calming that performance is now competitive with C++ https://medium.com/dartlang/dart2native-a76c815e6baf
I have read on reddit that AOT performance for rest api server is not good and it is recommended to use dart vm for peak load. Is this true?

**Comment by Ephenodrom** [comment]
Would be really nice.
It would be easier to have just a single file for deployment than handling multiple files. 

Currently doing this with some command line tools written in Dart. I am looking forward for this feature combined with Aqueduct.

**Comment by mnordine** [comment]
@joeconwaystk Is this related? https://github.com/stablekernel/aqueduct/commit/16fc395f24d5ebde0c35b8d76caa8add3c25ef43

**Comment by devisions** [comment]
@ansarizafar Just for the sake of keeping things clean, can you close this ticket and we should all refer to #669  on this subject?
